### ISSUE TITLE
add circleci integration

### ISSUE THREAD

**Issue by nottakis** [baby-degu/docusaurus#16]
Please add the CircleCI Integration. 
https://docusaurus.io/docs/en/publishing#using-circleci-20

**Comment by ryuckel** [comment]
I think we should create account and talk about account management including #18 #20 .

**Comment by nottakis** [comment]
You can create an account. CircleCI should be dependent on individual:)

**Comment by nottakis** [comment]
Github Action looks better than CircleCI so I switched it:)
