### ISSUE TITLE
Is there good replacement with this footerIcon?

### ISSUE THREAD

**Issue by nottakis** [baby-degu/docusaurus#19]
![Screen Shot 2020-05-16 at 13 55 05](https://user-images.githubusercontent.com/14342458/82111019-df851080-977c-11ea-912a-b3e67f59244b.png)

If we commented out, it looks terrible. 

![Screen Shot 2020-05-16 at 13 56 14](https://user-images.githubusercontent.com/14342458/82111047-08a5a100-977d-11ea-953b-573f101e0ba9.png)

We need to think of an excellent way to handle this.

**Comment by ryuckel** [comment]
How about baby-degu icon?

**Comment by nottakis** [comment]
It's good but we don't have .svg... 
We should ask someone to create our logo:/

**Comment by nottakis** [comment]
![Screen Shot 2020-06-03 at 15 28 28](https://user-images.githubusercontent.com/14342458/83603172-e69a8400-a5ae-11ea-92cf-2b654aa31108.png)

Set empty URL path. It looks alright.
