### ISSUE TITLE
connect slack for notification

### ISSUE THREAD

**Issue by ryuckel** [baby-degu/docusaurus#22]
How about connecting slack channel for notice our activity?

setting procedure is below.
https://qiita.com/unsoluble_sugar/items/e42ac352400598a24915

**Comment by nottakis** [comment]
Great! That is pretty helpful if we do! 
Can you do it instead of me? If you don't have enough permission in slack, tsurumaki-san will help you:) About the github, it's me.

**Comment by ryuckel** [comment]
OK! I will create channel for github notification!

**Comment by ryuckel** [comment]
@nottakis 
I requested an approvement to notice #_bell_github channel.
After you approve this request, notification is posted to this channel.

**Comment by nottakis** [comment]
I haven't got the request but where can I find it?
You have a same permission as me so I think I don't have to do anything.

**Comment by nottakis** [comment]
Sorry! I've found that!

**Comment by ryuckel** [comment]
Thanks! I've enabled notification! Please join #_bell_github if you want!

**Comment by nottakis** [comment]
I'm in:)
You can post about the channel on the #qiita or #general. :)

**Comment by ryuckel** [comment]
I posted #qiita channel!

**Comment by nottakis** [comment]
Great!
