### ISSUE TITLE
translation doesn't work on website/blog

### ISSUE THREAD

**Issue by nottakis** [baby-degu/docusaurus#3]

**Comment by nottakis** [comment]
It's a critical problem. We gotta fix it as soon as possible.

**Comment by ryuckel** [comment]
Could you give me expected work of this issue?
Does it work on crowdin or this website?

**Comment by nottakis** [comment]
I've already checked that translation itself works on the Crowdin. 
I thought that it doesn't work because of the configuration of this repo, but according to the document, it looks like it's an automatic process, so maybe my configuration of Crowdin is wrong somehow. 

https://docusaurus.io/docs/en/translation#markdown-files

I've tested on my own Crowdin account. 
I think it's hard to fix this issue without checking the Crowdin. So if you don't mind me asking you to check that, that's really helpful. 
*Anyway we do use Crowdin to translate the contents...

**Comment by nottakis** [comment]
( It might be hard to apply translated .md on website/blog. Maybe we can use docs/ )

**Comment by ryuckel** [comment]
How about changing file path of source section at crowdin.yaml?
I want to try it if I can. However, I could not catch how to translate .md file.....

**Comment by nottakis** [comment]
OK. It takes some time but let me try:)

**Comment by nottakis** [comment]
Translation doesn't work on website/blog by default. 
I guess this is because blog posts are not something worth to translate, or it shouldn't. 
translation of docs/ folder works. At this time, we need to set CROWDIN_DOCUSAURUS_PROJECT_ID and CROWDIN_DOCUSAURUS_API_KEY manually, but circleCI configuration will solve this problem. 
https://github.com/baby-degu/docusaurus/issues/23
