### ISSUE TITLE
setup members section

### ISSUE THREAD

**Issue by nottakis** [baby-degu/docusaurus#5]

**Comment by nottakis** [comment]
Why don't we show our commitments to outsiders?

**Comment by ryuckel** [comment]
How about setting contents from profile of qiita?

**Comment by nottakis** [comment]
You mean the baby-degu profile on Qiita?
That's all right, but I thought that our community members should be in the members section. 
* I don't know what it should be look like though.

**Comment by nottakis** [comment]
You can set yourself in the Users section:)

**Comment by nottakis** [comment]
I set up a pioneer section. (It's not fixed though)
Anyway, I'll close this issue.
